### ISSUE TITLE
Error clicking item in GUI

### ISSUE THREAD

**Issue by FiveEYZ** [Time6628/Market#4]
Updated to Market-0.2.1 and are using HuskyUI-v0.2.1

when i click an item that is for sale in the GUI (looks really aweosme, good job) the GUI will close and the clicked item will drop on the ground
[![Screenshot from Gyazo](https://gyazo.com/7b411c6df7bae3263b272853ce5d5605/raw)](https://gyazo.com/7b411c6df7bae3263b272853ce5d5605)

Error:
https://gist.github.com/FiveEYZ/2a93de998f3e9be6e1f531084e0bad5b

Full log:
https://gist.githubusercontent.com/FiveEYZ/8137f9e329f04c839a072a4ef7a09f82/raw/919e9aa5350aa3fd703b59b7babd2bee7463cb29/fml-server-latest.log

**Comment by Time6628** [comment]
Most likely fixed in the latest version of HuskyUI.

**Comment by FiveEYZ** [comment]
still happening with latest HuskyUI-v0.3.0

https://gist.github.com/FiveEYZ/cae8331dae6c12308aabc0c45d62c793

**Comment by Time6628** [comment]
The GUI is not meant for production, it's still in heavy development.

**Comment by FiveEYZ** [comment]
Well now you know there is a issue with it, glad I could help find it for you.

Thanks for making this plugin possible!

**Comment by codeHusky** [comment]
Hello Time.
This issue really has nothing to do with HuskyUI. It's an issue with the way you're using RunnableActions, which is causing a Sponge Phase Change exception of the sorts. A better way to handle this is to call a method directly rather than running a command to open the GUIs.

**Comment by Time6628** [comment]
Don't use RunnableActions anymore, here is the current code:
```java
    @Override
    public StateContainer getListingsGUI() {
        try (Jedis jedis = getJedis().getResource()) {
            //create new state container
            StateContainer sc = new StateContainer();
            //get all the listings for sale
            Set<String> openListings = jedis.hgetAll(RedisKeys.FOR_SALE).keySet();
            //create a new page builder
            Page.PageBuilder p = Page.builder().setAutoPaging(true).setTitle(Texts.MARKET_BASE).setInventoryDimension(InventoryDimension.of(6,6)).setEmptyStack(ItemStack.builder().itemType(ItemTypes.STAINED_GLASS_PANE).add(Keys.DYE_COLOR, DyeColors.GREEN).add(Keys.DISPLAY_NAME, Text.of("")).build());
            //add all the listings to the pages
            openListings.forEach(ol -> {
                //get the listing info
                Map<String, String> listing = jedis.hgetAll(RedisKeys.MARKET_ITEM_KEY(ol));
                //check if the item can be deserialized
                Optional<ItemStack> is = plugin.deserializeItemStack(listing.get("Item"));
                is.ifPresent(itemStack -> {
                    //get the item stack
                    ItemStack i = is.get().copy();
                    i.setQuantity(Integer.valueOf(listing.get("Quantity")));
                    List<Text> lore = new ArrayList<>();
                    lore.add(Texts.guiListing.apply(listing).build());
                    lore.add(Text.builder().color(TextColors.WHITE).append(Text.of("Seller: " + jedis.hget(RedisKeys.UUID_CACHE, listing.get("Seller")))).build());

                    i.offer(Keys.ITEM_LORE, lore);

                    CommandAction ca = new CommandAction(sc, ActionType.CLOSE, "1", ("market check " + ol), CommandAction.CommandReceiver.PLAYER);

                    p.addElement(new ActionableElement(ca, i));
                });
            });
            sc.setInitialState(p.build("0"));
            sc.addState(new State("1"));
            return sc;
        }
    }
```
Although, this seems to not run the commands at all.

**Comment by codeHusky** [comment]
Fixed in v0.3.1 with fixes for CommandAction.
